#ifdef __cplusplus
extern "C" {
#endif

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Fri Feb 02 14:50:24 2024. */

#include "svcfirmware.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const int32_t SKF_SvcFirmwareUpdateNotification_version_default = 512;
const int32_t SKF_SvcFirmwareBlockRequest_version_default = 512;
const int32_t SKF_SvcFirmwareBlockReply_version_default = 512;


const pb_field_t SKF_SvcFirmwareUpdateNotification_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SKF_SvcFirmwareUpdateNotification, version, version, &SKF_SvcFirmwareUpdateNotification_version_default),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareUpdateNotification, source_id, version, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareUpdateNotification, message_id, source_id, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareUpdateNotification, device_type, message_id, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareUpdateNotification, hardware_version, device_type, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareUpdateNotification, firmware_version, hardware_version, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareUpdateNotification, image_size, firmware_version, 0),
    PB_LAST_FIELD
};

const pb_field_t SKF_SvcFirmwareBlockRequest_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SKF_SvcFirmwareBlockRequest, version, version, &SKF_SvcFirmwareBlockRequest_version_default),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareBlockRequest, source_id, version, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockRequest, message_id, source_id, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareBlockRequest, device_type, message_id, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockRequest, hardware_version, device_type, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockRequest, firmware_version, hardware_version, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockRequest, byte_index, firmware_version, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockRequest, block_size, byte_index, 0),
    PB_LAST_FIELD
};

const pb_field_t SKF_SvcFirmwareBlockReply_fields[10] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SKF_SvcFirmwareBlockReply, version, version, &SKF_SvcFirmwareBlockReply_version_default),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareBlockReply, source_id, version, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockReply, message_id, source_id, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareBlockReply, device_type, message_id, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockReply, hardware_version, device_type, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockReply, firmware_version, hardware_version, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockReply, byte_index, firmware_version, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, SKF_SvcFirmwareBlockReply, image_size, byte_index, 0),
    PB_FIELD(  9, BYTES   , REQUIRED, CALLBACK, OTHER, SKF_SvcFirmwareBlockReply, image, image_size, 0),
    PB_LAST_FIELD
};




#ifdef __cplusplus
}
#endif