#ifdef __cplusplus
extern "C" {
#endif

/*
 * configIDEFParam.h
 * Created on: 06 September 2017
 * Author: Automatically generated by idef_code_generator.py
 *
 * Definition of IDEF parameters and properties
 */


#ifndef CONFIGIDEFPARAM_H_
#define CONFIGIDEFPARAM_H_

#include "configFeatures.h"

// Definition helper macro, use property ID as upper 2 bytes of the parameter ID
#define IDEFPARAMID_ENUMVALUE(m_propid,m_paramid)    ((m_propid)<<16) + (m_paramid)


/**
 * IDEF_propid_t
 *
 * IDEF Property ID definitions
 */
typedef enum idefpropid_enum {
	IDEFPROPID_DEVICE_INFO                                     = 0x0001,
	IDEFPROPID_EVENT                                           = 0x0002,
	IDEFPROPID_COM_SETTINGS                                    = 0x0003,
	IDEFPROPID_ENERGY_MANAGEMENT                               = 0x0004,
	IDEFPROPID_TEMPERATURE                                     = 0x0005,
	IDEFPROPID_VIBRATION                                       = 0x0006,
	IDEFPROPID_GNSS                                            = 0x0007,
	IDEFPROPID_MOVEMENT                                        = 0x0008,
	IDEFPROPID_OPERATING_CONDITION                             = 0x0009,
	IDEFPROPID_SCHEDULING                                      = 0x000a,
	IDEFPROPID_DEVICE_ID                                       = 0x000b,
	IDEFPROPID_VERIFICATION                                    = 0xf000,
} IDEF_propid_t;

/**
 * IDEF_paramid_t
 *
 * IDEF Parameter ID definitions
 */
typedef enum idefparamid_enum {
	IDEFPARAMID_DEVICE_TYPE                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_INFO                     ,0x0001),
	IDEFPARAMID_DEVICE_DESCRIPTION                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_INFO                     ,0x0002),
	IDEFPARAMID_DEVICE_SERIAL_NUMBER                            = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_INFO                     ,0x0003),
	IDEFPARAMID_HARDWARE_VERSION                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_INFO                     ,0x0004),
	IDEFPARAMID_FIRMWARE_VERSION                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_INFO                     ,0x0005),
	IDEFPARAMID_UP_TIME                                         = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0006),
	IDEFPARAMID_IS_SELF_TEST_SUCCESSFUL                         = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0007),
	IDEFPARAMID_STATUS_SELF_TEST                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0008),
	IDEFPARAMID_URL_SERVER_1                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_COM_SETTINGS                    ,0x0009),
	IDEFPARAMID_URL_SERVER_2                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_COM_SETTINGS                    ,0x000a),
	IDEFPARAMID_URL_SERVER_3                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_COM_SETTINGS                    ,0x000b),
	IDEFPARAMID_URL_SERVER_4                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_COM_SETTINGS                    ,0x000c),
	IDEFPARAMID_IS_UPLOAD_OFFSET_ENABLED                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_COM_SETTINGS                    ,0x000d),
	IDEFPARAMID_ENERGY_REMAINING                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x000e),
	IDEFPARAMID_TEMPERATURE_ALARM_UPPER_LIMIT                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_TEMPERATURE                     ,0x000f),
	IDEFPARAMID_TEMPERATURE_ALARM_LOWER_LIMIT                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_TEMPERATURE                     ,0x0010),
	IDEFPARAMID_TEMPERATURE_PCB                                 = IDEFPARAMID_ENUMVALUE(IDEFPROPID_TEMPERATURE                     ,0x0011),
	IDEFPARAMID_TEMPERATURE_EXTERNAL                            = IDEFPARAMID_ENUMVALUE(IDEFPROPID_TEMPERATURE                     ,0x0012),
	IDEFPARAMID_SAMPLE_RATE_RAW                                 = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0013),
	IDEFPARAMID_SAMPLES_RAW                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0014),
	IDEFPARAMID_SAMPLE_RATE_BEARING                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0015),
	IDEFPARAMID_SAMPLES_BEARING                                 = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0016),
	IDEFPARAMID_IS_RAW_ACCELERATION_ENABLED                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0017),
	IDEFPARAMID_ACCELERATION_ENV3                               = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0018),
	IDEFPARAMID_ACCELERATION_RAW                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0019),
	IDEFPARAMID_ACCELERATION_Y                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x001a),
	IDEFPARAMID_ACCELERATION_X                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x001b),
	IDEFPARAMID_ACCELERATION_Z                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x001c),
	IDEFPARAMID_SCALING_BEARING                                 = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x001d),
	IDEFPARAMID_SCALING_RAW                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x001e),
	IDEFPARAMID_IS_VERBOSE_LOGGING_ENABLED                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03e8),
	IDEFPARAMID_GNSS_LAT_1                                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03e9),
	IDEFPARAMID_GNSS_NS_1                                       = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03ea),
	IDEFPARAMID_GNSS_LONG_1                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03eb),
	IDEFPARAMID_GNSS_EW_1                                       = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03ec),
	IDEFPARAMID_GNSS_SPEED_TO_ROTATION_1                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03ed),
	IDEFPARAMID_GNSS_COURSE_1                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03ee),
	IDEFPARAMID_GNSS_TIME_TO_FIX_1                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03ef),
	IDEFPARAMID_GNSS_TIME_DIFF                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03f0),
	IDEFPARAMID_GNSS_SPEED_TO_ROTATION_2                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03f1),
	IDEFPARAMID_GNSS_SAT_ID                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03f2),
	IDEFPARAMID_GNSS_SAT_SNR                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_GNSS                            ,0x03f3),
	IDEFPARAMID_ROTATION_DIFF                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_MOVEMENT                        ,0x03f4),
	IDEFPARAMID_IS_MOVE_DETECT_MEAS                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_MOVEMENT                        ,0x03f5),
	IDEFPARAMID_IS_MOVING_GATING_ENABLED                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_MOVEMENT                        ,0x03f6),
	IDEFPARAMID_COM_TIMESTAMP                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x03f7),
	IDEFPARAMID_WAKEUP_REASON                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x03f8),
	IDEFPARAMID_COM_SIGNAL_QUALITY                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x03f9),
	IDEFPARAMID_IS_COM_SUCCESSFUL                               = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x03fa),
	IDEFPARAMID_CONFIRM_UPLOAD                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x03fb),
	IDEFPARAMID_IS_MOVE_DETECT_COM                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x03fc),
	IDEFPARAMID_HUMIDITY                                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x03fd),
	IDEFPARAMID_SENSOR_LOCATION_ANGLE                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x03fe),
	IDEFPARAMID_SENSOR_ORIENTATION_ANGLE                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x03ff),
	IDEFPARAMID_GNSS_LAT_COM                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0400),
	IDEFPARAMID_GNSS_NS_COM                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0401),
	IDEFPARAMID_GNSS_LONG_COM                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0402),
	IDEFPARAMID_GNSS_EW_COM                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0403),
	IDEFPARAMID_GNSS_SPEED_TO_ROTATION_COM                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0404),
	IDEFPARAMID_TIME_LAST_WAKE                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0405),
	IDEFPARAMID_TIME_ELAP_REGISTRATION                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0406),
	IDEFPARAMID_TIME_ELAP_TCP_CONNECT                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0407),
	IDEFPARAMID_TIME_ELAP_TCP_DISCONNECT                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0408),
	IDEFPARAMID_TIME_ELAP_MODEM_ON                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_EVENT                           ,0x0409),
	IDEFPARAMID_V_0                                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x040a),
	IDEFPARAMID_V_1                                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x040b),
	IDEFPARAMID_V_2                                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x040c),
	IDEFPARAMID_E_GNSS_CYCLE                                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x040d),
	IDEFPARAMID_E_MODEM_CYCLE                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x040e),
	IDEFPARAMID_E_PREVIOUS_WAKE_CYCLE                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_ENERGY_MANAGEMENT               ,0x040f),
	IDEFPARAMID_SCHEDULE_ID                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x0410),
	IDEFPARAMID_ACCELERATION_WHEEL_FLAT_DETECT                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0411),
	IDEFPARAMID_IS_GOOD_SPEED_DIFF                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0412),
	IDEFPARAMID_MIN_HZ                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0413),
	IDEFPARAMID_MAX_HZ                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0414),
	IDEFPARAMID_ALLOWED_ROTATION_CHANGE                         = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0415),
	IDEFPARAMID_IS_SPEED_WITHIN_ENV                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0416),
	IDEFPARAMID_SAMPLE_RATE_WHEEL_FLAT                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0417),
	IDEFPARAMID_SAMPLES_WHEEL_FLAT                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0418),
	IDEFPARAMID_TIME_START_MEAS                                 = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x0419),
	IDEFPARAMID_RETRY_INTERVAL_MEAS                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x041a),
	IDEFPARAMID_MAX_DAILY_MEAS_RETRIES                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x041b),
	IDEFPARAMID_REQUIRED_DAILY_MEAS                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x041c),
	IDEFPARAMID_UPLOAD_TIME                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x041d),
	IDEFPARAMID_RETRY_INTERVAL_UPLOAD                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x041e),
	IDEFPARAMID_MAX_UPLOAD_RETRIES                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x041f),
	IDEFPARAMID_UPLOAD_REPEAT                                   = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x0420),
	IDEFPARAMID_NUMBER_OF_UPLOAD                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_SCHEDULING                      ,0x0421),
	IDEFPARAMID_ACCELERATION_THRESHOLD_MOVEMENT_DETECT          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0422),
	IDEFPARAMID_ACCELERATION_AVG_TIME_MOVEMENT_DETECT           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0423),
	IDEFPARAMID_IS_POWER_ON_FAILSAFE_ENABLED                    = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0424),
	IDEFPARAMID_TRAIN_OPERATOR                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0425),
	IDEFPARAMID_TRAIN_FLEET                                     = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0426),
	IDEFPARAMID_TRAIN_ID                                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0427),
	IDEFPARAMID_VEHICLE_ID                                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0428),
	IDEFPARAMID_VEHICLE_NICKNAME                                = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0429),
	IDEFPARAMID_BOGIE_SERIAL_NUMBER                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x042a),
	IDEFPARAMID_WHEELSET_NUMBER                                 = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x042b),
	IDEFPARAMID_WHEELSET_SERIAL_NUMBER                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x042c),
	IDEFPARAMID_IS_WHEELSET_DRIVEN                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x042d),
	IDEFPARAMID_WHEEL_SERIAL_NUMBER                             = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x042e),
	IDEFPARAMID_WHEEL_SIDE                                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x042f),
	IDEFPARAMID_WHEEL_DIAMETER                                  = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0430),
	IDEFPARAMID_AXLEBOX_SERIAL_NUMBER                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0431),
	IDEFPARAMID_BEARING_BRAND_MODEL_NUMBER                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0432),
	IDEFPARAMID_BEARING_SERIAL_NUMBER                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0433),
	IDEFPARAMID_IMEI                                            = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_ID                       ,0x0434),
	IDEFPARAMID_ICCID                                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_DEVICE_ID                       ,0x0435),
	IDEFPARAMID_SCALING_WHEEL_FLAT                              = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VIBRATION                       ,0x0436),
	IDEFPARAMID_TRAIN_NAME                                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0437),
	IDEFPARAMID_BOGIE_NUMBER_IN_WAGON                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_OPERATING_CONDITION             ,0x0438),
#ifdef CONFIG_PLATFORM_IDEFSVCTESTDATA
	IDEFTEST_BOOL                                            = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf000),
	IDEFTEST_BYTE                                            = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf001),
	IDEFTEST_SBYTE                                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf002),
	IDEFTEST_INT16                                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf003),
	IDEFTEST_UINT16                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf004),
	IDEFTEST_INT32                                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf005),
	IDEFTEST_UINT32                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf006),
	IDEFTEST_INT64                                           = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf007),
	IDEFTEST_UINT64                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf008),
	IDEFTEST_SINGLE                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf009),
	IDEFTEST_DOUBLE                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf00a),
	IDEFTEST_STRING                                          = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf00b),
	IDEFTEST_DATETIME                                        = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf00c),
	IDEFTEST_UINT32A                                         = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf00d),
	IDEFTEST_UINT32ABIG                                      = IDEFPARAMID_ENUMVALUE(IDEFPROPID_VERIFICATION                    ,0xf00e),
#endif /* CONFIG_PLATFORM_IDEFSVCTESTDATA */
} IDEF_paramid_t;

#ifdef DEBUG

const char * IDEF_paramid_to_str(IDEF_paramid_t e);

const char * IDEF_propid_to_str(IDEF_propid_t e);


#endif /* DEBUG */

#endif /* CONFIGIDEFPARAM_H_ */


#ifdef __cplusplus
}
#endif