#ifdef __cplusplus
extern "C" {
#endif

/*
 * configIDEFParam.c
 * Created on: 06 September 2017
 * Author: Automatically generated by idef_code_generator.py
 *
 * IDEF parameters and property to string function
 */

#include "configIDEFParam.h"

#ifdef DEBUG

/**
 * IDEF_paramid_to_str
 *
 * IDEF_paramid_to_str
 */
const char * IDEF_paramid_to_str(IDEF_paramid_t e){
	return 
	((e) == IDEFPARAMID_DEVICE_TYPE                             ) ? "DEVICE_TYPE" :
	((e) == IDEFPARAMID_DEVICE_DESCRIPTION                      ) ? "DEVICE_DESCRIPTION" :
	((e) == IDEFPARAMID_DEVICE_SERIAL_NUMBER                    ) ? "DEVICE_SERIAL_NUMBER" :
	((e) == IDEFPARAMID_HARDWARE_VERSION                        ) ? "HARDWARE_VERSION" :
	((e) == IDEFPARAMID_FIRMWARE_VERSION                        ) ? "FIRMWARE_VERSION" :
	((e) == IDEFPARAMID_UP_TIME                                 ) ? "UP_TIME" :
	((e) == IDEFPARAMID_IS_SELF_TEST_SUCCESSFUL                 ) ? "IS_SELF_TEST_SUCCESSFUL" :
	((e) == IDEFPARAMID_STATUS_SELF_TEST                        ) ? "STATUS_SELF_TEST" :
	((e) == IDEFPARAMID_URL_SERVER_1                            ) ? "URL_SERVER_1" :
	((e) == IDEFPARAMID_URL_SERVER_2                            ) ? "URL_SERVER_2" :
	((e) == IDEFPARAMID_URL_SERVER_3                            ) ? "URL_SERVER_3" :
	((e) == IDEFPARAMID_URL_SERVER_4                            ) ? "URL_SERVER_4" :
	((e) == IDEFPARAMID_IS_UPLOAD_OFFSET_ENABLED                ) ? "IS_UPLOAD_OFFSET_ENABLED" :
	((e) == IDEFPARAMID_ENERGY_REMAINING                        ) ? "ENERGY_REMAINING" :
	((e) == IDEFPARAMID_TEMPERATURE_ALARM_UPPER_LIMIT           ) ? "TEMPERATURE_ALARM_UPPER_LIMIT" :
	((e) == IDEFPARAMID_TEMPERATURE_ALARM_LOWER_LIMIT           ) ? "TEMPERATURE_ALARM_LOWER_LIMIT" :
	((e) == IDEFPARAMID_TEMPERATURE_PCB                         ) ? "TEMPERATURE_PCB" :
	((e) == IDEFPARAMID_TEMPERATURE_EXTERNAL                    ) ? "TEMPERATURE_EXTERNAL" :
	((e) == IDEFPARAMID_SAMPLE_RATE_RAW                         ) ? "SAMPLE_RATE_RAW" :
	((e) == IDEFPARAMID_SAMPLES_RAW                             ) ? "SAMPLES_RAW" :
	((e) == IDEFPARAMID_SAMPLE_RATE_BEARING                     ) ? "SAMPLE_RATE_BEARING" :
	((e) == IDEFPARAMID_SAMPLES_BEARING                         ) ? "SAMPLES_BEARING" :
	((e) == IDEFPARAMID_IS_RAW_ACCELERATION_ENABLED             ) ? "IS_RAW_ACCELERATION_ENABLED" :
	((e) == IDEFPARAMID_ACCELERATION_ENV3                       ) ? "ACCELERATION_ENV3" :
	((e) == IDEFPARAMID_ACCELERATION_RAW                        ) ? "ACCELERATION_RAW" :
	((e) == IDEFPARAMID_ACCELERATION_Y                          ) ? "ACCELERATION_Y" :
	((e) == IDEFPARAMID_ACCELERATION_X                          ) ? "ACCELERATION_X" :
	((e) == IDEFPARAMID_ACCELERATION_Z                          ) ? "ACCELERATION_Z" :
	((e) == IDEFPARAMID_SCALING_BEARING                         ) ? "SCALING_BEARING" :
	((e) == IDEFPARAMID_SCALING_RAW                             ) ? "SCALING_RAW" :
	((e) == IDEFPARAMID_IS_VERBOSE_LOGGING_ENABLED              ) ? "IS_VERBOSE_LOGGING_ENABLED" :
	((e) == IDEFPARAMID_GNSS_LAT_1                              ) ? "GNSS_LAT_1" :
	((e) == IDEFPARAMID_GNSS_NS_1                               ) ? "GNSS_NS_1" :
	((e) == IDEFPARAMID_GNSS_LONG_1                             ) ? "GNSS_LONG_1" :
	((e) == IDEFPARAMID_GNSS_EW_1                               ) ? "GNSS_EW_1" :
	((e) == IDEFPARAMID_GNSS_SPEED_TO_ROTATION_1                ) ? "GNSS_SPEED_TO_ROTATION_1" :
	((e) == IDEFPARAMID_GNSS_COURSE_1                           ) ? "GNSS_COURSE_1" :
	((e) == IDEFPARAMID_GNSS_TIME_TO_FIX_1                      ) ? "GNSS_TIME_TO_FIX_1" :
	((e) == IDEFPARAMID_GNSS_TIME_DIFF                          ) ? "GNSS_TIME_DIFF" :
	((e) == IDEFPARAMID_GNSS_SPEED_TO_ROTATION_2                ) ? "GNSS_SPEED_TO_ROTATION_2" :
	((e) == IDEFPARAMID_GNSS_SAT_ID                             ) ? "GNSS_SAT_ID" :
	((e) == IDEFPARAMID_GNSS_SAT_SNR                            ) ? "GNSS_SAT_SNR" :
	((e) == IDEFPARAMID_ROTATION_DIFF                           ) ? "ROTATION_DIFF" :
	((e) == IDEFPARAMID_IS_MOVE_DETECT_MEAS                     ) ? "IS_MOVE_DETECT_MEAS" :
	((e) == IDEFPARAMID_IS_MOVING_GATING_ENABLED                ) ? "IS_MOVING_GATING_ENABLED" :
	((e) == IDEFPARAMID_COM_TIMESTAMP                           ) ? "COM_TIMESTAMP" :
	((e) == IDEFPARAMID_WAKEUP_REASON                           ) ? "WAKEUP_REASON" :
	((e) == IDEFPARAMID_COM_SIGNAL_QUALITY                      ) ? "COM_SIGNAL_QUALITY" :
	((e) == IDEFPARAMID_IS_COM_SUCCESSFUL                       ) ? "IS_COM_SUCCESSFUL" :
	((e) == IDEFPARAMID_CONFIRM_UPLOAD                          ) ? "CONFIRM_UPLOAD" :
	((e) == IDEFPARAMID_IS_MOVE_DETECT_COM                      ) ? "IS_MOVE_DETECT_COM" :
	((e) == IDEFPARAMID_HUMIDITY                                ) ? "HUMIDITY" :
	((e) == IDEFPARAMID_SENSOR_LOCATION_ANGLE                   ) ? "SENSOR_LOCATION_ANGLE" :
	((e) == IDEFPARAMID_SENSOR_ORIENTATION_ANGLE                ) ? "SENSOR_ORIENTATION_ANGLE" :
	((e) == IDEFPARAMID_GNSS_LAT_COM                            ) ? "GNSS_LAT_COM" :
	((e) == IDEFPARAMID_GNSS_NS_COM                             ) ? "GNSS_NS_COM" :
	((e) == IDEFPARAMID_GNSS_LONG_COM                           ) ? "GNSS_LONG_COM" :
	((e) == IDEFPARAMID_GNSS_EW_COM                             ) ? "GNSS_EW_COM" :
	((e) == IDEFPARAMID_GNSS_SPEED_TO_ROTATION_COM              ) ? "GNSS_SPEED_TO_ROTATION_COM" :
	((e) == IDEFPARAMID_TIME_LAST_WAKE                          ) ? "TIME_LAST_WAKE" :
	((e) == IDEFPARAMID_TIME_ELAP_REGISTRATION                  ) ? "TIME_ELAP_REGISTRATION" :
	((e) == IDEFPARAMID_TIME_ELAP_TCP_CONNECT                   ) ? "TIME_ELAP_TCP_CONNECT" :
	((e) == IDEFPARAMID_TIME_ELAP_TCP_DISCONNECT                ) ? "TIME_ELAP_TCP_DISCONNECT" :
	((e) == IDEFPARAMID_TIME_ELAP_MODEM_ON                      ) ? "TIME_ELAP_MODEM_ON" :
	((e) == IDEFPARAMID_V_0                                     ) ? "V_0" :
	((e) == IDEFPARAMID_V_1                                     ) ? "V_1" :
	((e) == IDEFPARAMID_V_2                                     ) ? "V_2" :
	((e) == IDEFPARAMID_E_GNSS_CYCLE                            ) ? "E_GNSS_CYCLE" :
	((e) == IDEFPARAMID_E_MODEM_CYCLE                           ) ? "E_MODEM_CYCLE" :
	((e) == IDEFPARAMID_E_PREVIOUS_WAKE_CYCLE                   ) ? "E_PREVIOUS_WAKE_CYCLE" :
	((e) == IDEFPARAMID_SCHEDULE_ID                             ) ? "SCHEDULE_ID" :
	((e) == IDEFPARAMID_ACCELERATION_WHEEL_FLAT_DETECT          ) ? "ACCELERATION_WHEEL_FLAT_DETECT" :
	((e) == IDEFPARAMID_IS_GOOD_SPEED_DIFF                      ) ? "IS_GOOD_SPEED_DIFF" :
	((e) == IDEFPARAMID_MIN_HZ                                  ) ? "MIN_HZ" :
	((e) == IDEFPARAMID_MAX_HZ                                  ) ? "MAX_HZ" :
	((e) == IDEFPARAMID_ALLOWED_ROTATION_CHANGE                 ) ? "ALLOWED_ROTATION_CHANGE" :
	((e) == IDEFPARAMID_IS_SPEED_WITHIN_ENV                     ) ? "IS_SPEED_WITHIN_ENV" :
	((e) == IDEFPARAMID_SAMPLE_RATE_WHEEL_FLAT                  ) ? "SAMPLE_RATE_WHEEL_FLAT" :
	((e) == IDEFPARAMID_SAMPLES_WHEEL_FLAT                      ) ? "SAMPLES_WHEEL_FLAT" :
	((e) == IDEFPARAMID_TIME_START_MEAS                         ) ? "TIME_START_MEAS" :
	((e) == IDEFPARAMID_RETRY_INTERVAL_MEAS                     ) ? "RETRY_INTERVAL_MEAS" :
	((e) == IDEFPARAMID_MAX_DAILY_MEAS_RETRIES                  ) ? "MAX_DAILY_MEAS_RETRIES" :
	((e) == IDEFPARAMID_REQUIRED_DAILY_MEAS                     ) ? "REQUIRED_DAILY_MEAS" :
	((e) == IDEFPARAMID_UPLOAD_TIME                             ) ? "UPLOAD_TIME" :
	((e) == IDEFPARAMID_RETRY_INTERVAL_UPLOAD                   ) ? "RETRY_INTERVAL_UPLOAD" :
	((e) == IDEFPARAMID_MAX_UPLOAD_RETRIES                      ) ? "MAX_UPLOAD_RETRIES" :
	((e) == IDEFPARAMID_UPLOAD_REPEAT                           ) ? "UPLOAD_REPEAT" :
	((e) == IDEFPARAMID_NUMBER_OF_UPLOAD                        ) ? "NUMBER_OF_UPLOAD" :
	((e) == IDEFPARAMID_ACCELERATION_THRESHOLD_MOVEMENT_DETECT  ) ? "ACCELERATION_THRESHOLD_MOVEMENT_DETECT" :
	((e) == IDEFPARAMID_ACCELERATION_AVG_TIME_MOVEMENT_DETECT   ) ? "ACCELERATION_AVG_TIME_MOVEMENT_DETECT" :
	((e) == IDEFPARAMID_IS_POWER_ON_FAILSAFE_ENABLED            ) ? "IS_POWER_ON_FAILSAFE_ENABLED" :
	((e) == IDEFPARAMID_TRAIN_OPERATOR                          ) ? "TRAIN_OPERATOR" :
	((e) == IDEFPARAMID_TRAIN_FLEET                             ) ? "TRAIN_FLEET" :
	((e) == IDEFPARAMID_TRAIN_ID                                ) ? "TRAIN_ID" :
	((e) == IDEFPARAMID_VEHICLE_ID                              ) ? "VEHICLE_ID" :
	((e) == IDEFPARAMID_VEHICLE_NICKNAME                        ) ? "VEHICLE_NICKNAME" :
	((e) == IDEFPARAMID_BOGIE_SERIAL_NUMBER                     ) ? "BOGIE_SERIAL_NUMBER" :
	((e) == IDEFPARAMID_WHEELSET_NUMBER                         ) ? "WHEELSET_NUMBER" :
	((e) == IDEFPARAMID_WHEELSET_SERIAL_NUMBER                  ) ? "WHEELSET_SERIAL_NUMBER" :
	((e) == IDEFPARAMID_IS_WHEELSET_DRIVEN                      ) ? "IS_WHEELSET_DRIVEN" :
	((e) == IDEFPARAMID_WHEEL_SERIAL_NUMBER                     ) ? "WHEEL_SERIAL_NUMBER" :
	((e) == IDEFPARAMID_WHEEL_SIDE                              ) ? "WHEEL_SIDE" :
	((e) == IDEFPARAMID_WHEEL_DIAMETER                          ) ? "WHEEL_DIAMETER" :
	((e) == IDEFPARAMID_AXLEBOX_SERIAL_NUMBER                   ) ? "AXLEBOX_SERIAL_NUMBER" :
	((e) == IDEFPARAMID_BEARING_BRAND_MODEL_NUMBER              ) ? "BEARING_BRAND_MODEL_NUMBER" :
	((e) == IDEFPARAMID_BEARING_SERIAL_NUMBER                   ) ? "BEARING_SERIAL_NUMBER" :
	((e) == IDEFPARAMID_IMEI                                    ) ? "IMEI" :
	((e) == IDEFPARAMID_ICCID                                   ) ? "ICCID" :
	((e) == IDEFPARAMID_SCALING_WHEEL_FLAT                      ) ? "SCALING_WHEEL_FLAT" :
	((e) == IDEFPARAMID_TRAIN_NAME                              ) ? "TRAIN_NAME" :
	((e) == IDEFPARAMID_BOGIE_NUMBER_IN_WAGON                   ) ? "BOGIE_NUMBER_IN_WAGON" :
#ifdef CONFIG_PLATFORM_IDEFSVCTESTDATA
	((e) == IDEFTEST_BOOL                                    ) ? "BOOL" :
	((e) == IDEFTEST_BYTE                                    ) ? "BYTE" :
	((e) == IDEFTEST_SBYTE                                   ) ? "SBYTE" :
	((e) == IDEFTEST_INT16                                   ) ? "INT16" :
	((e) == IDEFTEST_UINT16                                  ) ? "UINT16" :
	((e) == IDEFTEST_INT32                                   ) ? "INT32" :
	((e) == IDEFTEST_UINT32                                  ) ? "UINT32" :
	((e) == IDEFTEST_INT64                                   ) ? "INT64" :
	((e) == IDEFTEST_UINT64                                  ) ? "UINT64" :
	((e) == IDEFTEST_SINGLE                                  ) ? "SINGLE" :
	((e) == IDEFTEST_DOUBLE                                  ) ? "DOUBLE" :
	((e) == IDEFTEST_STRING                                  ) ? "STRING" :
	((e) == IDEFTEST_DATETIME                                ) ? "DATETIME" :
	((e) == IDEFTEST_UINT32A                                 ) ? "UINT32A" :
	((e) == IDEFTEST_UINT32ABIG                              ) ? "UINT32ABIG" :
#endif /* CONFIG_PLATFORM_IDEFSVCTESTDATA */
		"unknown";
}

/**
 * IDEF_propid_to_str
 *
 * IDEF_propertyid_to_str
 */
const char * IDEF_propid_to_str(IDEF_propid_t e){
	return 
	((e) == IDEFPROPID_DEVICE_INFO                             ) ? "Device_Info" :
	((e) == IDEFPROPID_EVENT                                   ) ? "Event" :
	((e) == IDEFPROPID_COM_SETTINGS                            ) ? "Com_Settings" :
	((e) == IDEFPROPID_ENERGY_MANAGEMENT                       ) ? "Energy_Management" :
	((e) == IDEFPROPID_TEMPERATURE                             ) ? "Temperature" :
	((e) == IDEFPROPID_VIBRATION                               ) ? "Vibration" :
	((e) == IDEFPROPID_GNSS                                    ) ? "GNSS" :
	((e) == IDEFPROPID_MOVEMENT                                ) ? "Movement" :
	((e) == IDEFPROPID_OPERATING_CONDITION                     ) ? "Operating_Condition" :
	((e) == IDEFPROPID_SCHEDULING                              ) ? "Scheduling" :
	((e) == IDEFPROPID_DEVICE_ID                               ) ? "Device_Id" :
	((e) == IDEFPROPID_VERIFICATION                            ) ? "Verification" :
		"unknown";
}

#endif /* DEBUG */


#ifdef __cplusplus
}
#endif