#ifdef __cplusplus
extern "C" {
#endif

/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : KSDK1.h
**     Project     : freertos_trace
**     Processor   : MK64FN1M0VLL12
**     Component   : KinetisSDK
**     Version     : Component 01.001, Driver 01.00, CPU db: 3.00.000
**     Repository  : UserComponents_20151122
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-29, 12:28, # CodeGen: 2
**     Abstract    :
**
**     Settings    :
**          Component name                                 : KSDK1
**     Contents    :
**         No public methods
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2014, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing waiting routines using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file KSDK1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup KSDK1_module KSDK1 module documentation
**  @{
*/         

#ifndef __KSDK1_H
#define __KSDK1_H

/* MODULE KSDK1. */

/* Include inherited beans */
#include "PE_KSDK_Types.h" /* if this file is missing: have you added the Kinetis SDK component? */



/* END KSDK1. */

#endif
/* ifndef __KSDK1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/


#ifdef __cplusplus
}
#endif