#ifdef __cplusplus
extern "C" {
#endif

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Fri Feb 02 14:50:23 2024. */

#include "svccommon.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SKF_Value_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, SKF_Value, value_type, value_type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, SKF_Value, data, value_type, 0),
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionBeginReq_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionBeginRep_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SKF_TransactionBeginRep, trans_id, trans_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionCommitReq_fields[3] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, SKF_TransactionCommitReq, trans_id, trans_id, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, SKF_TransactionCommitReq, trans_seq, trans_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionCommitRep_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionRollbackReq_fields[2] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, SKF_TransactionRollbackReq, trans_id, trans_id, 0),
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionRollbackRep_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SKF_TransactionInfo_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SKF_TransactionInfo, trans_id, trans_id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SKF_TransactionInfo, trans_seq, trans_id, 0),
    PB_LAST_FIELD
};




#ifdef __cplusplus
}
#endif